# SPDX-License-Identifier: PMPL-1.0-or-later
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>

name = "VeriSimDBClient"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.10"
HTTP = "1"
JSON3 = "1"
URIs = "1"
